http_server:
  host: 0.0.0.0
  port: 8001

feishu_app:
  app_id: cli_a61e57b76e38901b
  app_secret: u9O5VPkv7ZEI8oPUvdLeKfrhYUDuC41x

inner_logs:
  log_level: debug
  console:
    enable: true
  file:
    enable: true
    filename: /var/log/apaas_ob_agent/run.log
    seg_dua: day
    max_age: 30
  loki:
    enable: true
    schema: http
    host: 127.0.0.1 # 替换成 docker network 中 loki 的 ip
    port: 3100
    labels: {
      service_name: apaas_agent
    }


prometheus:
  function_exec_duration_milliseconds_histogram: {
    name: function_exec_duration_seconds_histogram,
    type: histogram,
    label_names: [ tenant_id, namespace, env,
                   function_api_name, language, is_long_task, is_front_end_access_enabled,
                   exec_result, trigger_type ],
    buckets: [ 300, 500, 1000, 1500, 2000, 4000, 8000, 10000, 30000, 60000, 300000, 600000, 900000, 3600000, 5400000, 7200000, 9000000 ]
  }

  function_exec_duration_milliseconds_summary: {
    name: function_exec_duration_seconds_summary,
    type: summary,
    label_names: [ tenant_id, namespace, env,
                   function_api_name, language, is_long_task, is_front_end_access_enabled,
                   exec_result, trigger_type ],
    objectives: {
      0.5: 0.05,
      0.9: 0.01,
      0.95: 0.005,
      0.99: 0.001,
      0.999: 0.0001
    }
  }

  oapi_call_duration_milliseconds_histogram: {
    name: oapi_call_duration_milliseconds_histogram,
    type: histogram,
    label_names: [ tenant_id, namespace, env,
                   method, path, version, client_id, response_code, error_code ],
    buckets: [ 300, 500, 1000, 1500, 2000, 4000, 8000 ]
  }

  oapi_call_duration_milliseconds_summary: {
    name: oapi_call_duration_milliseconds_summary,
    type: summary,
    label_names: [ tenant_id, namespace, env,
                   method, path, version, client_id, response_code, error_code ],
    objectives: {
      0.5: 0.05,
      0.9: 0.01,
      0.95: 0.005,
      0.99: 0.001,
      0.999: 0.0001
    }
  }